### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by shigadeyo** [mapster/WeightyBeer#1]
This is a really great project and exactly what I was looking for as I have been interested in setting up something to monitor the levels of my kegs. I have several questions and concerns that I have listed below for your consideration:

1. It's possible to connect multiple scales by using an HX711 for each one, connecting each of those to the Arduino, and then adding a sensor for each in the weightsensor/config.json file to define the pins used, correct? I have 4 kegs that I would like to track, so I would have four scales and HX711 connected to various pin paris on the Arduino.
2. Is an [Arduino Uno R3 mainboard](https://www.microcenter.com/product/486544/uno-r3-mainboard) sufficient? 
3. The Arduino gets connected to the Raspberry Pi via USB and the Pi is running the weightsensor component?
4. Is a [Raspberry Pi Zero W](https://www.microcenter.com/product/486575/zero-w) (1 Ghz single core, 512MB) sufficient? 
5. Is it possible to run all of the components (weightsensor, weighthub, client) from the same Pi Zero?
6. How is scale drift due to temperature and constant weight load on the sensors being handled?
7. How often is the weight being sampled and sent to Firebase for storage? A very large concern is exceeding the free level of read/writes/data for Firebase and Firestore and getting billed for it. This concern increases as the number of kegs (currently 4) increases. Any information on how the measurement data is limited to prevent this would be appreciated.
8. Since it has been 2 years since the last update, is this project still being maintained? How has everything held up over time?

I look forward to your response. Thank you and keep up the great work!

**Comment by mapster** [comment]
Thank you. The reason I haven't made any changes to the project in two years is that it is still running on my Pi under the keg fridge. So it's not that it is not maintained any longer, it's that it has been working and there hasn't really been any need to change it. My motivation for creating it was two-fold; (1) monitoring my kegs without having to open the fridge and awkwardly lifting the kegs to get a feeling of how much is left, and (2) learn a couple of new (for me) technologies. 

1. Yes, I'm already using it for three kegs with weights under them in my setup. I guess the only limit (within reason) is the numer of pins you have available. Since the weightsensor component is standalone you could also expand with multiple Pi's and Arduino's if you've used up all the pin-pairs.
1. It is sufficient for three kegs as it only has six anologue pins. 
1. Correct. You also need to flash the arduino with the rom.
1. The software does not have high compute requirements and I would think that it should be good enough, though I cannot guarantee it. The arduino rom reads the sensors with a one-second delay, and the nodejs script simply submits those readings to firebase.
1. I run them from my rasperry pi (Raspberry Pi 2 Model B).
1. I've never gotten around to looking into these potential issues. WeightyBeer doesn't rely on the actual weight of the kegs, but rather the difference between sensor-readings from an empty keg and a full keg. So whenever you put a new keg in you should re-calibrate it's associated sensor.
1. I've been using it with three kegs for two years without exceeding the free limit of Firebase. The default behavior for the arduino-rom is to submit sensor readings with a one-second delay, and the weightsensor script submits data as soon as it receives it. If you surpass the free-limit the easiest way to limit the use of firebase is to reduce the sample rate, though that will affect the accuracy of the readings. It looks like the free-limits of the realtime database is measured in GB stored and GB downloaded, but the limits of the new Firestore (which replaced realtime database) has document writes/reads as limits. The weightsensor will exceed those limits if readings are submitted each second, so I'm in a lucky legacy situation.
1. I guess I'm repeating myself now, but it has held up above expectation during the last two years with little to no service needed. The weighthub component has a tendency to fail sometimes and needs to be restarted, but it has happened so rarely that I haven's seen the need to address it.

**Comment by shigadeyo** [comment]
Thank you for your response. I really appreciate it! Given that I have have an extra Raspberry Pi Zero W on hand the other components are relatively inexpensive, I have added this to my project list. However, I will need to investigate the DB options more and see about attempting to code something as I don't have an older Google Realtime Database account and want to avoid the costs associated with Firestore. 

Also, you mentioned the analog inputs on the Arduino. From the other examples I have seen for the HX711, I was under the impression that it they are usually connected via the digital input pins. If so, that would allow for up to 6 pairs on the Arduino Uno R3 mainboard.

**Comment by mapster** [comment]
Sorry for the late reply. I came to the same conclusion as you did when looking at the current documentation that I found, and then I got really uncertain if I remembered correctly that I was using the analog pins. I wasn't really motivated to dig out the devices and look at how it all is connected. I finally did look at it tonight, and found that I am indeed using the analog pins. I did some quick experiments using [bodge's HX711 library](https://github.com/bogde/HX711), and found that I was only able to read the sensors using the analog pins.

**Comment by mapster** [comment]
I got inspired and started working on an alternative solution that uses Redis for communication between `weightsensor` and `weighthub`, which will severly limit the number of requests to Firebase. Firebase will (almost) only be involved when the weight changes, e.g. tapping a beer or movement of the kegs. Adding an alternative to Firebase in the web-client will be significantly more work, and I will probably not do that for now.

**Comment by shigadeyo** [comment]
> Sorry for the late reply. I came to the same conclusion as you did when looking at the current documentation that I found, and then I got really uncertain if I remembered correctly that I was using the analog pins. I wasn't really motivated to dig out the devices and look at how it all is connected. I finally did look at it tonight, and found that I am indeed using the analog pins. I did some quick experiments using [bodge's HX711 library](https://github.com/bogde/HX711), and found that I was only able to read the sensors using the analog pins.

Thanks for the double check and response. I definitely appreciate it as I plan to turn my attention to implementing WeightyBeer for my kegs once I finish up making the collar and installing the taps. Those upgrades are long overdue since I am sick of messing with the picnic taps inside the keezer over the past few years!

**Comment by shigadeyo** [comment]
> I got inspired and started working on an alternative solution that uses Redis for communication between `weightsensor` and `weighthub`, which will severly limit the number of requests to Firebase. Firebase will (almost) only be involved when the weight changes, e.g. tapping a beer or movement of the kegs. Adding an alternative to Firebase in the web-client will be significantly more work, and I will probably not do that for now.
> 
> edit: You can track my progress in the `redis` branch.

Awesome! Very exciting. Glad you got inspired. Your efforts are not in vain as I look forward to setting up WeightyBeer for myself and another buddy may follow suit behind me. I will keep an eye on your progress since this is the next project on my list once I finish getting my collar and taps installed and my new brew stand built. So many overdue upgrades!

**Comment by mapster** [comment]
The new non-firebase implementation is feature complete and I've started using it myself as well.
